spring.application.name=ChurchRegistry
server.port=8084
spring.datasource.url=jdbc:postgresql://localhost:5432/church_register_dev
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Liquibase configuration
spring.liquibase.change-log=classpath:/db/changelog/changelog-master.xml

