
spring:
  h2:
    console:
      enabled: true

#  datasource:
#    username: sa
#    password: ""
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
  datasource:
    username: church_reg_dev_user
    password: "Welcome2024!"
    url: jdbc:postgresql://localhost:5432/church_register_dev
    driverClassName: org.postgresql.Driver


  liquibaseDatasource:
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    driverClassName: ${spring.datasource.driverClassName}

  liquibase:
    enabled: true
    contexts: local
    change-log: classpath:/db/changelog/changelog-master.xml
    default-schema: church_registry
  application:
    name: ChurchRegistry
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    database: postgresql
server:
  port: 8084

