
spring:
  h2:
    console:
      enabled: true

  datasource:
    username: church_reg_dev_user
    password: "Welcome2024!"
    url: jdbc:postgresql://localhost:5432/church_register_dev
    driverClassName: org.postgresql.Driver

  liquibaseDatasource:
    username: sa
    password: ""
    url: jdbc:h2:mem:testdb;MODE=Oracle;INIT=CREATE SCHEMA IF NO EXIST CHURCH_REGISTRY
    driverClassName: org.h2.Driver

  liquibase:
    enabled: true
    contexts: local
    change-log: classpath:/db/changelog/changelog-master.xml
  application:
    name: ChurchRegistry
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
server:
  port: 8084

#  spring.application.name=ChurchRegistry
#  server.port=8084
#  spring.datasource.url=jdbc:postgresql://localhost:5432/church_register_dev
#  spring.datasource.username=
#  spring.datasource.password=
#  spring.jpa.hibernate.ddl-auto=create-drop
#  spring.jpa.show-sql=true
#  spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#  spring.jpa.properties.hibernate.format_sql=true
#
#  # Liquibase configuration
#  spring.liquibase.change-log=classpath:/db/changelog/changelog-master.xml
#
#  spring.h2.console.enabled=true

